[package]
name = "ipfs_cluster"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
reqwest = { version = "0.11.11", default-features = false, features = ["multipart"] }
serde = "1"

[dev-dependencies]
tokio = "1"
