[package]
name = "ipfs_cluster"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["multipart"] }
anyhow = "1"
serde = "1"
log = "0.4"

[dev-dependencies]
tokio = "1"